import {Theme} from "./Theme";

export const QUEST_TYPES = ['side', 'main', 'chore', 'weekly', 'daily'];

export const QUEST_TIMING = ['unlimited', 'date', 'time', 'custom'];

export const QUEST_VISIBILITY = ['private', 'protected', 'public'];

export const AVATARS = [
	'basket_yellow',
	'bathroom_cleaner',
	'aluminum_foil',
	'American_cheese_p',
	'bacon',
	'baking_powder',
	'ball_pen',
	'banana',
	'white_cheese_piece',
	'white_cheese_piece_p',
	'wine_red',
	'wine_white',
	'wine_white2',
	'wine_white3',
	'toothpaste',
	'toothpaste_box',
	'tuna_can',
	'vanilla_or_lemon_ice_cream',
	'water',
	'watermelon1',
	'watermelon2',
	'wax',
	'wet_wipe',
	'whisk',
	'whisk_p',
	'white_cheese',
	'white_cheese_p',
	'soft_drink_green',
	'soft_drink_red',
	'soft_drink_yellow',
	'spatula',
	'spatula_p',
	'strawberry',
	'strawberry_ice_cream',
	'strawberry_jam',
	'strawberry_p',
	'sugar',
	'sun_cream_tube',
	'teakettle',
	'toilet_paper',
	'toothbrush',
	'toothbrush_set',
	'salmon',
	'salmon_p',
	'salt',
	'sausage_p',
	'scissors',
	'scissors_p',
	'scrub_brush',
	'scrub_sponge',
	'shampoo',
	'sliced_bread_p',
	'snack1',
	'snack2',
	'soap',
	'soap_box',
	'soft_drink_blue',
	'potato_p',
	'potatochip_blue',
	'potatochip_green',
	'potatochip_yellow',
	'power_strip_typeA',
	'power_strip_typeF',
	'receipt',
	'red_apple',
	'red_apple_p',
	'red_grape',
	'red_grape_p',
	'rolling pin',
	'rubber_duck',
	'rubber_ducktopus',
	'milk_chocolate',
	'milk_gallon',
	'milk_pack',
	'milk_plastic',
	'mushroom_white',
	'mushroom_white_p',
	'mustard',
	'olive_oil',
	'orange_juice',
	'paper_bag',
	'peanut_butter',
	'pencil_box',
	'plain_yogurt',
	'potato',
	'green_grape_p',
	'hand_sanitiser',
	'hot_cocoa_mix',
	'jam_strawberry',
	'ketchup',
	'kitchen_knife_set',
	'kitchen_knife_set_p',
	'kitchen_soap',
	'light_bulb',
	'light_bulb_box',
	'marshmallows',
	'meat1',
	'meat1_p',
	'meat2',
	'meat2_p',
	'milk_bottle',
	'eraser',
	'eraser_p',
	'fish',
	'fish_p',
	'flour',
	'fruit_cocktail_can',
	'frying pan',
	'frying pan_p',
	'glue',
	'glue_p',
	'glue_stick',
	'grape_soda',
	'green_apple',
	'green_apple_p',
	'green_grape',
	'cleaning_gloves',
	'cleaning_gloves_p',
	'coffee_bag',
	'cookies',
	'cooking_oil',
	'credit_card_1',
	'credit_card_2',
	'credit_card_3',
	'detergent',
	'dry_dog_food',
	'egg_box',
	'egg_brown',
	'egg_brown_p',
	'egg_white',
	'egg_white_p',
	'energy_bar',
	'batteries',
	'bell_pepper',
	'bell_pepper_p',
	'body_lotion',
	'bowl',
	'bubble_gum',
	'butter',
	'butter2',
	'cabbage',
	'cabbage_p',
	'candy_bar',
	'cereal1',
	'cereal2',
	'chopping board',
	'cleaning_brush',
	'bandage_box',
	'barbeque_sauce',
	'basket_metal'
];




